version: '3.7'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: agremiados
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge